// <autogenerated />
namespace Porticle.CLDR.Units
{
    public enum Unit
    {
        /// <summary>
        /// g-force (acceleration-g-force)
        /// </summary>
        AccelerationGForce = 0,

        /// <summary>
        /// meters per second squared (acceleration-meter-per-square-second)
        /// </summary>
        AccelerationMeterPerSquareSecond = 1,

        /// <summary>
        /// arcminutes (angle-arc-minute)
        /// </summary>
        AngleArcMinute = 2,

        /// <summary>
        /// arcseconds (angle-arc-second)
        /// </summary>
        AngleArcSecond = 3,

        /// <summary>
        /// degrees (angle-degree)
        /// </summary>
        AngleDegree = 4,

        /// <summary>
        /// radians (angle-radian)
        /// </summary>
        AngleRadian = 5,

        /// <summary>
        /// revolutions (angle-revolution)
        /// </summary>
        AngleRevolution = 6,

        /// <summary>
        /// acres (area-acre)
        /// </summary>
        AreaAcre = 7,

        /// <summary>
        /// AreaBuJp (area-bu-jp)
        /// </summary>
        AreaBuJp = 8,

        /// <summary>
        /// AreaCho (area-cho)
        /// </summary>
        AreaCho = 9,

        /// <summary>
        /// dunams (area-dunam)
        /// </summary>
        AreaDunam = 10,

        /// <summary>
        /// hectares (area-hectare)
        /// </summary>
        AreaHectare = 11,

        /// <summary>
        /// AreaSeJp (area-se-jp)
        /// </summary>
        AreaSeJp = 12,

        /// <summary>
        /// square centimeters (area-square-centimeter)
        /// </summary>
        AreaSquareCentimeter = 13,

        /// <summary>
        /// square feet (area-square-foot)
        /// </summary>
        AreaSquareFoot = 14,

        /// <summary>
        /// square inches (area-square-inch)
        /// </summary>
        AreaSquareInch = 15,

        /// <summary>
        /// square kilometers (area-square-kilometer)
        /// </summary>
        AreaSquareKilometer = 16,

        /// <summary>
        /// square meters (area-square-meter)
        /// </summary>
        AreaSquareMeter = 17,

        /// <summary>
        /// square miles (area-square-mile)
        /// </summary>
        AreaSquareMile = 18,

        /// <summary>
        /// square yards (area-square-yard)
        /// </summary>
        AreaSquareYard = 19,

        /// <summary>
        /// items (concentr-item)
        /// </summary>
        ConcentrItem = 20,

        /// <summary>
        /// karats (concentr-karat)
        /// </summary>
        ConcentrKarat = 21,

        /// <summary>
        /// milligrams per deciliter (concentr-milligram-ofglucose-per-deciliter)
        /// </summary>
        ConcentrMilligramOfglucosePerDeciliter = 22,

        /// <summary>
        /// millimoles per liter (concentr-millimole-per-liter)
        /// </summary>
        ConcentrMillimolePerLiter = 23,

        /// <summary>
        /// moles (concentr-mole)
        /// </summary>
        ConcentrMole = 24,

        /// <summary>
        /// percent (concentr-percent)
        /// </summary>
        ConcentrPercent = 25,

        /// <summary>
        /// permille (concentr-permille)
        /// </summary>
        ConcentrPermille = 26,

        /// <summary>
        /// parts per million (concentr-permillion)
        /// </summary>
        ConcentrPermillion = 27,

        /// <summary>
        /// permyriad (concentr-permyriad)
        /// </summary>
        ConcentrPermyriad = 28,

        /// <summary>
        /// parts per billion (concentr-portion-per-1e9)
        /// </summary>
        ConcentrPortionPer1E9 = 29,

        /// <summary>
        /// liters per 100 kilometers (consumption-liter-per-100-kilometer)
        /// </summary>
        ConsumptionLiterPer100Kilometer = 30,

        /// <summary>
        /// liters per kilometer (consumption-liter-per-kilometer)
        /// </summary>
        ConsumptionLiterPerKilometer = 31,

        /// <summary>
        /// miles per gallon (consumption-mile-per-gallon)
        /// </summary>
        ConsumptionMilePerGallon = 32,

        /// <summary>
        /// miles per Imp. gallon (consumption-mile-per-gallon-imperial)
        /// </summary>
        ConsumptionMilePerGallonImperial = 33,

        /// <summary>
        /// bits (digital-bit)
        /// </summary>
        DigitalBit = 34,

        /// <summary>
        /// bytes (digital-byte)
        /// </summary>
        DigitalByte = 35,

        /// <summary>
        /// gigabits (digital-gigabit)
        /// </summary>
        DigitalGigabit = 36,

        /// <summary>
        /// gigabytes (digital-gigabyte)
        /// </summary>
        DigitalGigabyte = 37,

        /// <summary>
        /// kilobits (digital-kilobit)
        /// </summary>
        DigitalKilobit = 38,

        /// <summary>
        /// kilobytes (digital-kilobyte)
        /// </summary>
        DigitalKilobyte = 39,

        /// <summary>
        /// megabits (digital-megabit)
        /// </summary>
        DigitalMegabit = 40,

        /// <summary>
        /// megabytes (digital-megabyte)
        /// </summary>
        DigitalMegabyte = 41,

        /// <summary>
        /// petabytes (digital-petabyte)
        /// </summary>
        DigitalPetabyte = 42,

        /// <summary>
        /// terabits (digital-terabit)
        /// </summary>
        DigitalTerabit = 43,

        /// <summary>
        /// terabytes (digital-terabyte)
        /// </summary>
        DigitalTerabyte = 44,

        /// <summary>
        /// centuries (duration-century)
        /// </summary>
        DurationCentury = 45,

        /// <summary>
        /// days (duration-day)
        /// </summary>
        DurationDay = 46,

        /// <summary>
        /// DurationDayPerson (duration-day-person)
        /// </summary>
        DurationDayPerson = 47,

        /// <summary>
        /// decades (duration-decade)
        /// </summary>
        DurationDecade = 48,

        /// <summary>
        /// hours (duration-hour)
        /// </summary>
        DurationHour = 49,

        /// <summary>
        /// microseconds (duration-microsecond)
        /// </summary>
        DurationMicrosecond = 50,

        /// <summary>
        /// milliseconds (duration-millisecond)
        /// </summary>
        DurationMillisecond = 51,

        /// <summary>
        /// minutes (duration-minute)
        /// </summary>
        DurationMinute = 52,

        /// <summary>
        /// months (duration-month)
        /// </summary>
        DurationMonth = 53,

        /// <summary>
        /// nanoseconds (duration-nanosecond)
        /// </summary>
        DurationNanosecond = 54,

        /// <summary>
        /// nights (duration-night)
        /// </summary>
        DurationNight = 55,

        /// <summary>
        /// quarters (duration-quarter)
        /// </summary>
        DurationQuarter = 56,

        /// <summary>
        /// seconds (duration-second)
        /// </summary>
        DurationSecond = 57,

        /// <summary>
        /// weeks (duration-week)
        /// </summary>
        DurationWeek = 58,

        /// <summary>
        /// years (duration-year)
        /// </summary>
        DurationYear = 59,

        /// <summary>
        /// amperes (electric-ampere)
        /// </summary>
        ElectricAmpere = 60,

        /// <summary>
        /// milliamperes (electric-milliampere)
        /// </summary>
        ElectricMilliampere = 61,

        /// <summary>
        /// ohms (electric-ohm)
        /// </summary>
        ElectricOhm = 62,

        /// <summary>
        /// volts (electric-volt)
        /// </summary>
        ElectricVolt = 63,

        /// <summary>
        /// British thermal units (energy-british-thermal-unit)
        /// </summary>
        EnergyBritishThermalUnit = 64,

        /// <summary>
        /// calories (energy-calorie)
        /// </summary>
        EnergyCalorie = 65,

        /// <summary>
        /// electronvolts (energy-electronvolt)
        /// </summary>
        EnergyElectronvolt = 66,

        /// <summary>
        /// Calories (energy-foodcalorie)
        /// </summary>
        EnergyFoodcalorie = 67,

        /// <summary>
        /// joules (energy-joule)
        /// </summary>
        EnergyJoule = 68,

        /// <summary>
        /// kilocalories (energy-kilocalorie)
        /// </summary>
        EnergyKilocalorie = 69,

        /// <summary>
        /// kilojoules (energy-kilojoule)
        /// </summary>
        EnergyKilojoule = 70,

        /// <summary>
        /// kilowatt-hours (energy-kilowatt-hour)
        /// </summary>
        EnergyKilowattHour = 71,

        /// <summary>
        /// US therms (energy-therm-us)
        /// </summary>
        EnergyThermUs = 72,

        /// <summary>
        /// kilowatt-hours per 100 kilometers (force-kilowatt-hour-per-100-kilometer)
        /// </summary>
        ForceKilowattHourPer100Kilometer = 73,

        /// <summary>
        /// newtons (force-newton)
        /// </summary>
        ForceNewton = 74,

        /// <summary>
        /// pounds of force (force-pound-force)
        /// </summary>
        ForcePoundForce = 75,

        /// <summary>
        /// gigahertz (frequency-gigahertz)
        /// </summary>
        FrequencyGigahertz = 76,

        /// <summary>
        /// hertz (frequency-hertz)
        /// </summary>
        FrequencyHertz = 77,

        /// <summary>
        /// kilohertz (frequency-kilohertz)
        /// </summary>
        FrequencyKilohertz = 78,

        /// <summary>
        /// megahertz (frequency-megahertz)
        /// </summary>
        FrequencyMegahertz = 79,

        /// <summary>
        /// dots (graphics-dot)
        /// </summary>
        GraphicsDot = 80,

        /// <summary>
        /// dots per centimeter (graphics-dot-per-centimeter)
        /// </summary>
        GraphicsDotPerCentimeter = 81,

        /// <summary>
        /// dots per inch (graphics-dot-per-inch)
        /// </summary>
        GraphicsDotPerInch = 82,

        /// <summary>
        /// typographic ems (graphics-em)
        /// </summary>
        GraphicsEm = 83,

        /// <summary>
        /// megapixels (graphics-megapixel)
        /// </summary>
        GraphicsMegapixel = 84,

        /// <summary>
        /// pixels (graphics-pixel)
        /// </summary>
        GraphicsPixel = 85,

        /// <summary>
        /// pixels per centimeter (graphics-pixel-per-centimeter)
        /// </summary>
        GraphicsPixelPerCentimeter = 86,

        /// <summary>
        /// pixels per inch (graphics-pixel-per-inch)
        /// </summary>
        GraphicsPixelPerInch = 87,

        /// <summary>
        /// astronomical units (length-astronomical-unit)
        /// </summary>
        LengthAstronomicalUnit = 88,

        /// <summary>
        /// centimeters (length-centimeter)
        /// </summary>
        LengthCentimeter = 89,

        /// <summary>
        /// decimeters (length-decimeter)
        /// </summary>
        LengthDecimeter = 90,

        /// <summary>
        /// earth radius (length-earth-radius)
        /// </summary>
        LengthEarthRadius = 91,

        /// <summary>
        /// fathoms (length-fathom)
        /// </summary>
        LengthFathom = 92,

        /// <summary>
        /// feet (length-foot)
        /// </summary>
        LengthFoot = 93,

        /// <summary>
        /// furlongs (length-furlong)
        /// </summary>
        LengthFurlong = 94,

        /// <summary>
        /// inches (length-inch)
        /// </summary>
        LengthInch = 95,

        /// <summary>
        /// LengthJoJp (length-jo-jp)
        /// </summary>
        LengthJoJp = 96,

        /// <summary>
        /// LengthKen (length-ken)
        /// </summary>
        LengthKen = 97,

        /// <summary>
        /// kilometers (length-kilometer)
        /// </summary>
        LengthKilometer = 98,

        /// <summary>
        /// light years (length-light-year)
        /// </summary>
        LengthLightYear = 99,

        /// <summary>
        /// meters (length-meter)
        /// </summary>
        LengthMeter = 100,

        /// <summary>
        /// micrometers (length-micrometer)
        /// </summary>
        LengthMicrometer = 101,

        /// <summary>
        /// miles (length-mile)
        /// </summary>
        LengthMile = 102,

        /// <summary>
        /// miles-scandinavian (length-mile-scandinavian)
        /// </summary>
        LengthMileScandinavian = 103,

        /// <summary>
        /// millimeters (length-millimeter)
        /// </summary>
        LengthMillimeter = 104,

        /// <summary>
        /// nanometers (length-nanometer)
        /// </summary>
        LengthNanometer = 105,

        /// <summary>
        /// nautical miles (length-nautical-mile)
        /// </summary>
        LengthNauticalMile = 106,

        /// <summary>
        /// parsecs (length-parsec)
        /// </summary>
        LengthParsec = 107,

        /// <summary>
        /// picometers (length-picometer)
        /// </summary>
        LengthPicometer = 108,

        /// <summary>
        /// points (length-point)
        /// </summary>
        LengthPoint = 109,

        /// <summary>
        /// LengthRiJp (length-ri-jp)
        /// </summary>
        LengthRiJp = 110,

        /// <summary>
        /// LengthRin (length-rin)
        /// </summary>
        LengthRin = 111,

        /// <summary>
        /// LengthShakuCloth (length-shaku-cloth)
        /// </summary>
        LengthShakuCloth = 112,

        /// <summary>
        /// LengthShakuLength (length-shaku-length)
        /// </summary>
        LengthShakuLength = 113,

        /// <summary>
        /// solar radii (length-solar-radius)
        /// </summary>
        LengthSolarRadius = 114,

        /// <summary>
        /// LengthSun (length-sun)
        /// </summary>
        LengthSun = 115,

        /// <summary>
        /// yards (length-yard)
        /// </summary>
        LengthYard = 116,

        /// <summary>
        /// candela (light-candela)
        /// </summary>
        LightCandela = 117,

        /// <summary>
        /// lumen (light-lumen)
        /// </summary>
        LightLumen = 118,

        /// <summary>
        /// lux (light-lux)
        /// </summary>
        LightLux = 119,

        /// <summary>
        /// solar luminosities (light-solar-luminosity)
        /// </summary>
        LightSolarLuminosity = 120,

        /// <summary>
        /// carats (mass-carat)
        /// </summary>
        MassCarat = 121,

        /// <summary>
        /// daltons (mass-dalton)
        /// </summary>
        MassDalton = 122,

        /// <summary>
        /// Earth masses (mass-earth-mass)
        /// </summary>
        MassEarthMass = 123,

        /// <summary>
        /// MassFun (mass-fun)
        /// </summary>
        MassFun = 124,

        /// <summary>
        /// grains (mass-grain)
        /// </summary>
        MassGrain = 125,

        /// <summary>
        /// grams (mass-gram)
        /// </summary>
        MassGram = 126,

        /// <summary>
        /// kilograms (mass-kilogram)
        /// </summary>
        MassKilogram = 127,

        /// <summary>
        /// micrograms (mass-microgram)
        /// </summary>
        MassMicrogram = 128,

        /// <summary>
        /// milligrams (mass-milligram)
        /// </summary>
        MassMilligram = 129,

        /// <summary>
        /// ounces (mass-ounce)
        /// </summary>
        MassOunce = 130,

        /// <summary>
        /// troy ounces (mass-ounce-troy)
        /// </summary>
        MassOunceTroy = 131,

        /// <summary>
        /// pounds (mass-pound)
        /// </summary>
        MassPound = 132,

        /// <summary>
        /// solar masses (mass-solar-mass)
        /// </summary>
        MassSolarMass = 133,

        /// <summary>
        /// stones (mass-stone)
        /// </summary>
        MassStone = 134,

        /// <summary>
        /// tons (mass-ton)
        /// </summary>
        MassTon = 135,

        /// <summary>
        /// metric tons (mass-tonne)
        /// </summary>
        MassTonne = 136,

        /// <summary>
        /// gigawatts (power-gigawatt)
        /// </summary>
        PowerGigawatt = 137,

        /// <summary>
        /// horsepower (power-horsepower)
        /// </summary>
        PowerHorsepower = 138,

        /// <summary>
        /// kilowatts (power-kilowatt)
        /// </summary>
        PowerKilowatt = 139,

        /// <summary>
        /// megawatts (power-megawatt)
        /// </summary>
        PowerMegawatt = 140,

        /// <summary>
        /// milliwatts (power-milliwatt)
        /// </summary>
        PowerMilliwatt = 141,

        /// <summary>
        /// watts (power-watt)
        /// </summary>
        PowerWatt = 142,

        /// <summary>
        /// atmospheres (pressure-atmosphere)
        /// </summary>
        PressureAtmosphere = 143,

        /// <summary>
        /// bars (pressure-bar)
        /// </summary>
        PressureBar = 144,

        /// <summary>
        /// of gasoline equivalent (pressure-gasoline-energy-density)
        /// </summary>
        PressureGasolineEnergyDensity = 145,

        /// <summary>
        /// hectopascals (pressure-hectopascal)
        /// </summary>
        PressureHectopascal = 146,

        /// <summary>
        /// inches of mercury (pressure-inch-ofhg)
        /// </summary>
        PressureInchOfhg = 147,

        /// <summary>
        /// kilopascals (pressure-kilopascal)
        /// </summary>
        PressureKilopascal = 148,

        /// <summary>
        /// megapascals (pressure-megapascal)
        /// </summary>
        PressureMegapascal = 149,

        /// <summary>
        /// millibars (pressure-millibar)
        /// </summary>
        PressureMillibar = 150,

        /// <summary>
        /// millimeters of mercury (pressure-millimeter-ofhg)
        /// </summary>
        PressureMillimeterOfhg = 151,

        /// <summary>
        /// pascals (pressure-pascal)
        /// </summary>
        PressurePascal = 152,

        /// <summary>
        /// pounds-force per square inch (pressure-pound-force-per-square-inch)
        /// </summary>
        PressurePoundForcePerSquareInch = 153,

        /// <summary>
        /// Beaufort (speed-beaufort)
        /// </summary>
        SpeedBeaufort = 154,

        /// <summary>
        /// kilometers per hour (speed-kilometer-per-hour)
        /// </summary>
        SpeedKilometerPerHour = 155,

        /// <summary>
        /// knots (speed-knot)
        /// </summary>
        SpeedKnot = 156,

        /// <summary>
        /// light (speed-light-speed)
        /// </summary>
        SpeedLightSpeed = 157,

        /// <summary>
        /// meters per second (speed-meter-per-second)
        /// </summary>
        SpeedMeterPerSecond = 158,

        /// <summary>
        /// miles per hour (speed-mile-per-hour)
        /// </summary>
        SpeedMilePerHour = 159,

        /// <summary>
        /// degrees Celsius (temperature-celsius)
        /// </summary>
        TemperatureCelsius = 160,

        /// <summary>
        /// degrees Fahrenheit (temperature-fahrenheit)
        /// </summary>
        TemperatureFahrenheit = 161,

        /// <summary>
        /// degrees temperature (temperature-generic)
        /// </summary>
        TemperatureGeneric = 162,

        /// <summary>
        /// kelvins (temperature-kelvin)
        /// </summary>
        TemperatureKelvin = 163,

        /// <summary>
        /// newton-meters (torque-newton-meter)
        /// </summary>
        TorqueNewtonMeter = 164,

        /// <summary>
        /// pound-force-feet (torque-pound-force-foot)
        /// </summary>
        TorquePoundForceFoot = 165,

        /// <summary>
        /// acre-feet (volume-acre-foot)
        /// </summary>
        VolumeAcreFoot = 166,

        /// <summary>
        /// barrels (volume-barrel)
        /// </summary>
        VolumeBarrel = 167,

        /// <summary>
        /// bushels (volume-bushel)
        /// </summary>
        VolumeBushel = 168,

        /// <summary>
        /// centiliters (volume-centiliter)
        /// </summary>
        VolumeCentiliter = 169,

        /// <summary>
        /// cubic centimeters (volume-cubic-centimeter)
        /// </summary>
        VolumeCubicCentimeter = 170,

        /// <summary>
        /// cubic feet (volume-cubic-foot)
        /// </summary>
        VolumeCubicFoot = 171,

        /// <summary>
        /// cubic inches (volume-cubic-inch)
        /// </summary>
        VolumeCubicInch = 172,

        /// <summary>
        /// cubic kilometers (volume-cubic-kilometer)
        /// </summary>
        VolumeCubicKilometer = 173,

        /// <summary>
        /// cubic meters (volume-cubic-meter)
        /// </summary>
        VolumeCubicMeter = 174,

        /// <summary>
        /// cubic miles (volume-cubic-mile)
        /// </summary>
        VolumeCubicMile = 175,

        /// <summary>
        /// cubic yards (volume-cubic-yard)
        /// </summary>
        VolumeCubicYard = 176,

        /// <summary>
        /// cups (volume-cup)
        /// </summary>
        VolumeCup = 177,

        /// <summary>
        /// VolumeCupJp (volume-cup-jp)
        /// </summary>
        VolumeCupJp = 178,

        /// <summary>
        /// metric cups (volume-cup-metric)
        /// </summary>
        VolumeCupMetric = 179,

        /// <summary>
        /// deciliters (volume-deciliter)
        /// </summary>
        VolumeDeciliter = 180,

        /// <summary>
        /// dessert spoons (volume-dessert-spoon)
        /// </summary>
        VolumeDessertSpoon = 181,

        /// <summary>
        /// Imp. dessert spoons (volume-dessert-spoon-imperial)
        /// </summary>
        VolumeDessertSpoonImperial = 182,

        /// <summary>
        /// drams (volume-dram)
        /// </summary>
        VolumeDram = 183,

        /// <summary>
        /// drops (volume-drop)
        /// </summary>
        VolumeDrop = 184,

        /// <summary>
        /// fluid ounces (volume-fluid-ounce)
        /// </summary>
        VolumeFluidOunce = 185,

        /// <summary>
        /// Imp. fluid ounces (volume-fluid-ounce-imperial)
        /// </summary>
        VolumeFluidOunceImperial = 186,

        /// <summary>
        /// gallons (volume-gallon)
        /// </summary>
        VolumeGallon = 187,

        /// <summary>
        /// Imp. gallons (volume-gallon-imperial)
        /// </summary>
        VolumeGallonImperial = 188,

        /// <summary>
        /// hectoliters (volume-hectoliter)
        /// </summary>
        VolumeHectoliter = 189,

        /// <summary>
        /// jiggers (volume-jigger)
        /// </summary>
        VolumeJigger = 190,

        /// <summary>
        /// VolumeKoku (volume-koku)
        /// </summary>
        VolumeKoku = 191,

        /// <summary>
        /// VolumeKosaji (volume-kosaji)
        /// </summary>
        VolumeKosaji = 192,

        /// <summary>
        /// liters (volume-liter)
        /// </summary>
        VolumeLiter = 193,

        /// <summary>
        /// megaliters (volume-megaliter)
        /// </summary>
        VolumeMegaliter = 194,

        /// <summary>
        /// milliliters (volume-milliliter)
        /// </summary>
        VolumeMilliliter = 195,

        /// <summary>
        /// VolumeOsaji (volume-osaji)
        /// </summary>
        VolumeOsaji = 196,

        /// <summary>
        /// pinches (volume-pinch)
        /// </summary>
        VolumePinch = 197,

        /// <summary>
        /// pints (volume-pint)
        /// </summary>
        VolumePint = 198,

        /// <summary>
        /// metric pints (volume-pint-metric)
        /// </summary>
        VolumePintMetric = 199,

        /// <summary>
        /// quarts (volume-quart)
        /// </summary>
        VolumeQuart = 200,

        /// <summary>
        /// Imp. quarts (volume-quart-imperial)
        /// </summary>
        VolumeQuartImperial = 201,

        /// <summary>
        /// VolumeSai (volume-sai)
        /// </summary>
        VolumeSai = 202,

        /// <summary>
        /// VolumeShaku (volume-shaku)
        /// </summary>
        VolumeShaku = 203,

        /// <summary>
        /// tablespoons (volume-tablespoon)
        /// </summary>
        VolumeTablespoon = 204,

        /// <summary>
        /// teaspoons (volume-teaspoon)
        /// </summary>
        VolumeTeaspoon = 205,

        /// <summary>
        /// VolumeToJp (volume-to-jp)
        /// </summary>
        VolumeToJp = 206,
    }
}
