// <autogenerated />
namespace Porticle.CLDR.Units
{
    public enum Unit
    {
        /// <summary>
        /// g-force (acceleration-g-force)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} g-force",shortFallback: "{0} G",narrowFallback: "{0}Gs")]
        AccelerationGForce = 0,

        /// <summary>
        /// meters per second squared (acceleration-meter-per-square-second)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} meters per second squared",shortFallback: "{0} m/s²",narrowFallback: "{0}m/s²")]
        AccelerationMeterPerSquareSecond = 1,

        /// <summary>
        /// arcminutes (angle-arc-minute)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} arcminutes",shortFallback: "{0} arcmins",narrowFallback: "{0}′")]
        AngleArcMinute = 2,

        /// <summary>
        /// arcseconds (angle-arc-second)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} arcseconds",shortFallback: "{0} arcsecs",narrowFallback: "{0}″")]
        AngleArcSecond = 3,

        /// <summary>
        /// degrees (angle-degree)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} degrees",shortFallback: "{0} deg",narrowFallback: "{0}°")]
        AngleDegree = 4,

        /// <summary>
        /// radians (angle-radian)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} radians",shortFallback: "{0} rad",narrowFallback: "{0}rad")]
        AngleRadian = 5,

        /// <summary>
        /// revolutions (angle-revolution)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} revolutions",shortFallback: "{0} rev",narrowFallback: "{0}rev")]
        AngleRevolution = 6,

        /// <summary>
        /// acres (area-acre)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} acres",shortFallback: "{0} ac",narrowFallback: "{0}ac")]
        AreaAcre = 7,

        /// <summary>
        /// AreaBuJp (area-bu-jp)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u6B69",shortFallback: "{0} 歩",narrowFallback: "{0}歩")]
        AreaBuJp = 8,

        /// <summary>
        /// AreaCho (area-cho)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u753A",shortFallback: "{0} 町",narrowFallback: "{0}町")]
        AreaCho = 9,

        /// <summary>
        /// dunams (area-dunam)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} dunams",shortFallback: "{0} dunam",narrowFallback: "{0}dunam")]
        AreaDunam = 10,

        /// <summary>
        /// hectares (area-hectare)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} hectares",shortFallback: "{0} ha",narrowFallback: "{0}ha")]
        AreaHectare = 11,

        /// <summary>
        /// AreaSeJp (area-se-jp)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u755D",shortFallback: "{0} 畝",narrowFallback: "{0}畝")]
        AreaSeJp = 12,

        /// <summary>
        /// square centimeters (area-square-centimeter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} square centimeters",shortFallback: "{0} cm²",narrowFallback: "{0}cm²")]
        AreaSquareCentimeter = 13,

        /// <summary>
        /// square feet (area-square-foot)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} square feet",shortFallback: "{0} sq ft",narrowFallback: "{0}ft²")]
        AreaSquareFoot = 14,

        /// <summary>
        /// square inches (area-square-inch)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} square inches",shortFallback: "{0} in²",narrowFallback: "{0}in²")]
        AreaSquareInch = 15,

        /// <summary>
        /// square kilometers (area-square-kilometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} square kilometers",shortFallback: "{0} km²",narrowFallback: "{0}km²")]
        AreaSquareKilometer = 16,

        /// <summary>
        /// square meters (area-square-meter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} square meters",shortFallback: "{0} m²",narrowFallback: "{0}m²")]
        AreaSquareMeter = 17,

        /// <summary>
        /// square miles (area-square-mile)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} square miles",shortFallback: "{0} sq mi",narrowFallback: "{0}mi²")]
        AreaSquareMile = 18,

        /// <summary>
        /// square yards (area-square-yard)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} square yards",shortFallback: "{0} yd²",narrowFallback: "{0}yd²")]
        AreaSquareYard = 19,

        /// <summary>
        /// items (concentr-item)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} items",shortFallback: "{0} items",narrowFallback: "{0}items")]
        ConcentrItem = 20,

        /// <summary>
        /// karats (concentr-karat)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} karats",shortFallback: "{0} kt",narrowFallback: "{0}kt")]
        ConcentrKarat = 21,

        /// <summary>
        /// milligrams per deciliter (concentr-milligram-ofglucose-per-deciliter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} milligrams per deciliter",shortFallback: "{0} mg/dL",narrowFallback: "{0}mg/dL")]
        ConcentrMilligramOfglucosePerDeciliter = 22,

        /// <summary>
        /// millimoles per liter (concentr-millimole-per-liter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} millimoles per liter",shortFallback: "{0} mmol/L",narrowFallback: "{0}mmol/L")]
        ConcentrMillimolePerLiter = 23,

        /// <summary>
        /// moles (concentr-mole)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} moles",shortFallback: "{0} mol",narrowFallback: "{0}mol")]
        ConcentrMole = 24,

        /// <summary>
        /// percent (concentr-percent)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} percent",shortFallback: "{0}%",narrowFallback: "{0}%")]
        ConcentrPercent = 25,

        /// <summary>
        /// permille (concentr-permille)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} permille",shortFallback: "{0}‰",narrowFallback: "{0}‰")]
        ConcentrPermille = 26,

        /// <summary>
        /// parts per million (concentr-permillion)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} parts per million",shortFallback: "{0} ppm",narrowFallback: "{0}ppm")]
        ConcentrPermillion = 27,

        /// <summary>
        /// permyriad (concentr-permyriad)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} permyriad",shortFallback: "{0}‱",narrowFallback: "{0}‱")]
        ConcentrPermyriad = 28,

        /// <summary>
        /// parts per billion (concentr-portion-per-1e9)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} parts per billion",shortFallback: "{0} ppb",narrowFallback: "{0}ppb")]
        ConcentrPortionPer1E9 = 29,

        /// <summary>
        /// liters per 100 kilometers (consumption-liter-per-100-kilometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} liters per 100 kilometers",shortFallback: "{0} L/100 km",narrowFallback: "{0}L/100km")]
        ConsumptionLiterPer100Kilometer = 30,

        /// <summary>
        /// liters per kilometer (consumption-liter-per-kilometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} liters per kilometer",shortFallback: "{0} L/km",narrowFallback: "{0}L/km")]
        ConsumptionLiterPerKilometer = 31,

        /// <summary>
        /// miles per gallon (consumption-mile-per-gallon)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} miles per gallon",shortFallback: "{0} mpg",narrowFallback: "{0}mpg")]
        ConsumptionMilePerGallon = 32,

        /// <summary>
        /// miles per Imp. gallon (consumption-mile-per-gallon-imperial)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} miles per Imp. gallon",shortFallback: "{0} mpg Imp.",narrowFallback: "{0}m/gUK")]
        ConsumptionMilePerGallonImperial = 33,

        /// <summary>
        /// bits (digital-bit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} bits",shortFallback: "{0} bit",narrowFallback: "{0}bit")]
        DigitalBit = 34,

        /// <summary>
        /// bytes (digital-byte)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} bytes",shortFallback: "{0} byte",narrowFallback: "{0}B")]
        DigitalByte = 35,

        /// <summary>
        /// gigabits (digital-gigabit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} gigabits",shortFallback: "{0} Gb",narrowFallback: "{0}Gb")]
        DigitalGigabit = 36,

        /// <summary>
        /// gigabytes (digital-gigabyte)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} gigabytes",shortFallback: "{0} GB",narrowFallback: "{0}GB")]
        DigitalGigabyte = 37,

        /// <summary>
        /// kilobits (digital-kilobit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilobits",shortFallback: "{0} kb",narrowFallback: "{0}kb")]
        DigitalKilobit = 38,

        /// <summary>
        /// kilobytes (digital-kilobyte)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilobytes",shortFallback: "{0} kB",narrowFallback: "{0}kB")]
        DigitalKilobyte = 39,

        /// <summary>
        /// megabits (digital-megabit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} megabits",shortFallback: "{0} Mb",narrowFallback: "{0}Mb")]
        DigitalMegabit = 40,

        /// <summary>
        /// megabytes (digital-megabyte)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} megabytes",shortFallback: "{0} MB",narrowFallback: "{0}MB")]
        DigitalMegabyte = 41,

        /// <summary>
        /// petabytes (digital-petabyte)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} petabytes",shortFallback: "{0} PB",narrowFallback: "{0}PB")]
        DigitalPetabyte = 42,

        /// <summary>
        /// terabits (digital-terabit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} terabits",shortFallback: "{0} Tb",narrowFallback: "{0}Tb")]
        DigitalTerabit = 43,

        /// <summary>
        /// terabytes (digital-terabyte)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} terabytes",shortFallback: "{0} TB",narrowFallback: "{0}TB")]
        DigitalTerabyte = 44,

        /// <summary>
        /// centuries (duration-century)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} centuries",shortFallback: "{0} c",narrowFallback: "{0}c")]
        DurationCentury = 45,

        /// <summary>
        /// days (duration-day)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} days",shortFallback: "{0} days",narrowFallback: "{0}d")]
        DurationDay = 46,

        /// <summary>
        /// DurationDayPerson (duration-day-person)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} Tage",shortFallback: "{0} Tage",narrowFallback: "{0} Tage")]
        DurationDayPerson = 47,

        /// <summary>
        /// decades (duration-decade)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} decades",shortFallback: "{0} dec",narrowFallback: "{0}dec")]
        DurationDecade = 48,

        /// <summary>
        /// hours (duration-hour)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} hours",shortFallback: "{0} hr",narrowFallback: "{0}h")]
        DurationHour = 49,

        /// <summary>
        /// microseconds (duration-microsecond)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} microseconds",shortFallback: "{0} μs",narrowFallback: "{0}μs")]
        DurationMicrosecond = 50,

        /// <summary>
        /// milliseconds (duration-millisecond)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} milliseconds",shortFallback: "{0} ms",narrowFallback: "{0}ms")]
        DurationMillisecond = 51,

        /// <summary>
        /// minutes (duration-minute)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} minutes",shortFallback: "{0} min",narrowFallback: "{0}m")]
        DurationMinute = 52,

        /// <summary>
        /// months (duration-month)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} months",shortFallback: "{0} mths",narrowFallback: "{0}m")]
        DurationMonth = 53,

        /// <summary>
        /// nanoseconds (duration-nanosecond)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} nanoseconds",shortFallback: "{0} ns",narrowFallback: "{0}ns")]
        DurationNanosecond = 54,

        /// <summary>
        /// nights (duration-night)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} nights",shortFallback: "{0} nights",narrowFallback: "{0}nights")]
        DurationNight = 55,

        /// <summary>
        /// quarters (duration-quarter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} quarters",shortFallback: "{0} qtrs",narrowFallback: "{0}q")]
        DurationQuarter = 56,

        /// <summary>
        /// seconds (duration-second)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} seconds",shortFallback: "{0} sec",narrowFallback: "{0}s")]
        DurationSecond = 57,

        /// <summary>
        /// weeks (duration-week)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} weeks",shortFallback: "{0} wks",narrowFallback: "{0}w")]
        DurationWeek = 58,

        /// <summary>
        /// years (duration-year)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} years",shortFallback: "{0} yrs",narrowFallback: "{0}y")]
        DurationYear = 59,

        /// <summary>
        /// amperes (electric-ampere)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} amperes",shortFallback: "{0} A",narrowFallback: "{0}A")]
        ElectricAmpere = 60,

        /// <summary>
        /// milliamperes (electric-milliampere)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} milliamperes",shortFallback: "{0} mA",narrowFallback: "{0}mA")]
        ElectricMilliampere = 61,

        /// <summary>
        /// ohms (electric-ohm)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} ohms",shortFallback: "{0} Ω",narrowFallback: "{0}Ω")]
        ElectricOhm = 62,

        /// <summary>
        /// volts (electric-volt)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} volts",shortFallback: "{0} V",narrowFallback: "{0}V")]
        ElectricVolt = 63,

        /// <summary>
        /// British thermal units (energy-british-thermal-unit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} British thermal units",shortFallback: "{0} Btu",narrowFallback: "{0}Btu")]
        EnergyBritishThermalUnit = 64,

        /// <summary>
        /// calories (energy-calorie)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} calories",shortFallback: "{0} cal",narrowFallback: "{0}cal")]
        EnergyCalorie = 65,

        /// <summary>
        /// electronvolts (energy-electronvolt)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} electronvolts",shortFallback: "{0} eV",narrowFallback: "{0}eV")]
        EnergyElectronvolt = 66,

        /// <summary>
        /// Calories (energy-foodcalorie)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} Calories",shortFallback: "{0} Cal",narrowFallback: "{0}Cal")]
        EnergyFoodcalorie = 67,

        /// <summary>
        /// joules (energy-joule)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} joules",shortFallback: "{0} J",narrowFallback: "{0}J")]
        EnergyJoule = 68,

        /// <summary>
        /// kilocalories (energy-kilocalorie)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilocalories",shortFallback: "{0} kcal",narrowFallback: "{0}kcal")]
        EnergyKilocalorie = 69,

        /// <summary>
        /// kilojoules (energy-kilojoule)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilojoules",shortFallback: "{0} kJ",narrowFallback: "{0}kJ")]
        EnergyKilojoule = 70,

        /// <summary>
        /// kilowatt-hours (energy-kilowatt-hour)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilowatt-hours",shortFallback: "{0} kWh",narrowFallback: "{0}kWh")]
        EnergyKilowattHour = 71,

        /// <summary>
        /// US therms (energy-therm-us)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} US therms",shortFallback: "{0} US therms",narrowFallback: "{0}US therms")]
        EnergyThermUs = 72,

        /// <summary>
        /// kilowatt-hours per 100 kilometers (force-kilowatt-hour-per-100-kilometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilowatt-hours per 100 kilometers",shortFallback: "{0} kWh/100km",narrowFallback: "{0}kWh/100km")]
        ForceKilowattHourPer100Kilometer = 73,

        /// <summary>
        /// newtons (force-newton)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} newtons",shortFallback: "{0} N",narrowFallback: "{0}N")]
        ForceNewton = 74,

        /// <summary>
        /// pounds of force (force-pound-force)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pounds of force",shortFallback: "{0} lbf",narrowFallback: "{0}lbf")]
        ForcePoundForce = 75,

        /// <summary>
        /// gigahertz (frequency-gigahertz)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} gigahertz",shortFallback: "{0} GHz",narrowFallback: "{0}GHz")]
        FrequencyGigahertz = 76,

        /// <summary>
        /// hertz (frequency-hertz)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} hertz",shortFallback: "{0} Hz",narrowFallback: "{0}Hz")]
        FrequencyHertz = 77,

        /// <summary>
        /// kilohertz (frequency-kilohertz)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilohertz",shortFallback: "{0} kHz",narrowFallback: "{0}kHz")]
        FrequencyKilohertz = 78,

        /// <summary>
        /// megahertz (frequency-megahertz)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} megahertz",shortFallback: "{0} MHz",narrowFallback: "{0}MHz")]
        FrequencyMegahertz = 79,

        /// <summary>
        /// dots (graphics-dot)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} dots",shortFallback: "{0} dots",narrowFallback: "{0}dot")]
        GraphicsDot = 80,

        /// <summary>
        /// dots per centimeter (graphics-dot-per-centimeter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} dots per centimeter",shortFallback: "{0} dpcm",narrowFallback: "{0}dpcm")]
        GraphicsDotPerCentimeter = 81,

        /// <summary>
        /// dots per inch (graphics-dot-per-inch)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} dots per inch",shortFallback: "{0} dpi",narrowFallback: "{0}dpi")]
        GraphicsDotPerInch = 82,

        /// <summary>
        /// typographic ems (graphics-em)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} ems",shortFallback: "{0} em",narrowFallback: "{0}em")]
        GraphicsEm = 83,

        /// <summary>
        /// megapixels (graphics-megapixel)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} megapixels",shortFallback: "{0} MP",narrowFallback: "{0}MP")]
        GraphicsMegapixel = 84,

        /// <summary>
        /// pixels (graphics-pixel)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pixels",shortFallback: "{0} px",narrowFallback: "{0}px")]
        GraphicsPixel = 85,

        /// <summary>
        /// pixels per centimeter (graphics-pixel-per-centimeter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pixels per centimeter",shortFallback: "{0} ppcm",narrowFallback: "{0}ppcm")]
        GraphicsPixelPerCentimeter = 86,

        /// <summary>
        /// pixels per inch (graphics-pixel-per-inch)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pixels per inch",shortFallback: "{0} ppi",narrowFallback: "{0}ppi")]
        GraphicsPixelPerInch = 87,

        /// <summary>
        /// astronomical units (length-astronomical-unit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} astronomical units",shortFallback: "{0} au",narrowFallback: "{0}au")]
        LengthAstronomicalUnit = 88,

        /// <summary>
        /// centimeters (length-centimeter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} centimeters",shortFallback: "{0} cm",narrowFallback: "{0}cm")]
        LengthCentimeter = 89,

        /// <summary>
        /// decimeters (length-decimeter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} decimeters",shortFallback: "{0} dm",narrowFallback: "{0}dm")]
        LengthDecimeter = 90,

        /// <summary>
        /// earth radius (length-earth-radius)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} earth radius",shortFallback: "{0} R⊕",narrowFallback: "{0}R⊕")]
        LengthEarthRadius = 91,

        /// <summary>
        /// fathoms (length-fathom)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} fathoms",shortFallback: "{0} fth",narrowFallback: "{0}fth")]
        LengthFathom = 92,

        /// <summary>
        /// feet (length-foot)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} feet",shortFallback: "{0} ft",narrowFallback: "{0}′")]
        LengthFoot = 93,

        /// <summary>
        /// furlongs (length-furlong)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} furlongs",shortFallback: "{0} fur",narrowFallback: "{0}fur")]
        LengthFurlong = 94,

        /// <summary>
        /// inches (length-inch)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} inches",shortFallback: "{0} in",narrowFallback: "{0}″")]
        LengthInch = 95,

        /// <summary>
        /// LengthJoJp (length-jo-jp)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u4E08",shortFallback: "{0} 丈",narrowFallback: "{0}丈")]
        LengthJoJp = 96,

        /// <summary>
        /// LengthKen (length-ken)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u9593",shortFallback: "{0} 間",narrowFallback: "{0}間")]
        LengthKen = 97,

        /// <summary>
        /// kilometers (length-kilometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilometers",shortFallback: "{0} km",narrowFallback: "{0}km")]
        LengthKilometer = 98,

        /// <summary>
        /// light years (length-light-year)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} light years",shortFallback: "{0} ly",narrowFallback: "{0}ly")]
        LengthLightYear = 99,

        /// <summary>
        /// meters (length-meter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} meters",shortFallback: "{0} m",narrowFallback: "{0}m")]
        LengthMeter = 100,

        /// <summary>
        /// micrometers (length-micrometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} micrometers",shortFallback: "{0} μm",narrowFallback: "{0}μm")]
        LengthMicrometer = 101,

        /// <summary>
        /// miles (length-mile)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} miles",shortFallback: "{0} mi",narrowFallback: "{0}mi")]
        LengthMile = 102,

        /// <summary>
        /// miles-scandinavian (length-mile-scandinavian)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} miles-scandinavian",shortFallback: "{0} smi",narrowFallback: "{0}smi")]
        LengthMileScandinavian = 103,

        /// <summary>
        /// millimeters (length-millimeter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} millimeters",shortFallback: "{0} mm",narrowFallback: "{0}mm")]
        LengthMillimeter = 104,

        /// <summary>
        /// nanometers (length-nanometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} nanometers",shortFallback: "{0} nm",narrowFallback: "{0}nm")]
        LengthNanometer = 105,

        /// <summary>
        /// nautical miles (length-nautical-mile)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} nautical miles",shortFallback: "{0} nmi",narrowFallback: "{0}nmi")]
        LengthNauticalMile = 106,

        /// <summary>
        /// parsecs (length-parsec)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} parsecs",shortFallback: "{0} pc",narrowFallback: "{0}pc")]
        LengthParsec = 107,

        /// <summary>
        /// picometers (length-picometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} picometers",shortFallback: "{0} pm",narrowFallback: "{0}pm")]
        LengthPicometer = 108,

        /// <summary>
        /// points (length-point)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} points",shortFallback: "{0} pt",narrowFallback: "{0}pt")]
        LengthPoint = 109,

        /// <summary>
        /// LengthRiJp (length-ri-jp)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u91CC",shortFallback: "{0} 里",narrowFallback: "{0}里")]
        LengthRiJp = 110,

        /// <summary>
        /// LengthRin (length-rin)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u5398",shortFallback: "{0} 厘",narrowFallback: "{0}厘")]
        LengthRin = 111,

        /// <summary>
        /// LengthShakuCloth (length-shaku-cloth)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u9BE8\u5C3A",shortFallback: "{0} 鯨尺",narrowFallback: "{0}鯨尺")]
        LengthShakuCloth = 112,

        /// <summary>
        /// LengthShakuLength (length-shaku-length)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u5C3A",shortFallback: "{0} 尺",narrowFallback: "{0}尺")]
        LengthShakuLength = 113,

        /// <summary>
        /// solar radii (length-solar-radius)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} solar radii",shortFallback: "{0} R☉",narrowFallback: "{0}R☉")]
        LengthSolarRadius = 114,

        /// <summary>
        /// LengthSun (length-sun)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u5BF8",shortFallback: "{0} 寸",narrowFallback: "{0}寸")]
        LengthSun = 115,

        /// <summary>
        /// yards (length-yard)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} yards",shortFallback: "{0} yd",narrowFallback: "{0}yd")]
        LengthYard = 116,

        /// <summary>
        /// candela (light-candela)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} candela",shortFallback: "{0} cd",narrowFallback: "{0}cd")]
        LightCandela = 117,

        /// <summary>
        /// lumen (light-lumen)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} lumen",shortFallback: "{0} lm",narrowFallback: "{0}lm")]
        LightLumen = 118,

        /// <summary>
        /// lux (light-lux)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} lux",shortFallback: "{0} lx",narrowFallback: "{0}lx")]
        LightLux = 119,

        /// <summary>
        /// solar luminosities (light-solar-luminosity)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} solar luminosities",shortFallback: "{0} L☉",narrowFallback: "{0}L☉")]
        LightSolarLuminosity = 120,

        /// <summary>
        /// carats (mass-carat)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} carats",shortFallback: "{0} CD",narrowFallback: "{0}CD")]
        MassCarat = 121,

        /// <summary>
        /// daltons (mass-dalton)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} daltons",shortFallback: "{0} Da",narrowFallback: "{0}Da")]
        MassDalton = 122,

        /// <summary>
        /// Earth masses (mass-earth-mass)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} Earth masses",shortFallback: "{0} M⊕",narrowFallback: "{0}M⊕")]
        MassEarthMass = 123,

        /// <summary>
        /// MassFun (mass-fun)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u5206 - \u8CEA\u91CF",shortFallback: "{0} 分 - 質量",narrowFallback: "{0}分")]
        MassFun = 124,

        /// <summary>
        /// grains (mass-grain)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} grains",shortFallback: "{0} gr",narrowFallback: "{0}gr")]
        MassGrain = 125,

        /// <summary>
        /// grams (mass-gram)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} grams",shortFallback: "{0} g",narrowFallback: "{0}g")]
        MassGram = 126,

        /// <summary>
        /// kilograms (mass-kilogram)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilograms",shortFallback: "{0} kg",narrowFallback: "{0}kg")]
        MassKilogram = 127,

        /// <summary>
        /// micrograms (mass-microgram)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} micrograms",shortFallback: "{0} μg",narrowFallback: "{0}μg")]
        MassMicrogram = 128,

        /// <summary>
        /// milligrams (mass-milligram)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} milligrams",shortFallback: "{0} mg",narrowFallback: "{0}mg")]
        MassMilligram = 129,

        /// <summary>
        /// ounces (mass-ounce)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} ounces",shortFallback: "{0} oz",narrowFallback: "{0}oz")]
        MassOunce = 130,

        /// <summary>
        /// troy ounces (mass-ounce-troy)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} troy ounces",shortFallback: "{0} oz t",narrowFallback: "{0}oz t")]
        MassOunceTroy = 131,

        /// <summary>
        /// pounds (mass-pound)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pounds",shortFallback: "{0} lb",narrowFallback: "{0}#")]
        MassPound = 132,

        /// <summary>
        /// solar masses (mass-solar-mass)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} solar masses",shortFallback: "{0} M☉",narrowFallback: "{0}M☉")]
        MassSolarMass = 133,

        /// <summary>
        /// stones (mass-stone)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} stones",shortFallback: "{0} st",narrowFallback: "{0}st")]
        MassStone = 134,

        /// <summary>
        /// tons (mass-ton)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} tons",shortFallback: "{0} tn",narrowFallback: "{0}tn")]
        MassTon = 135,

        /// <summary>
        /// metric tons (mass-tonne)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} metric tons",shortFallback: "{0} t",narrowFallback: "{0}t")]
        MassTonne = 136,

        /// <summary>
        /// gigawatts (power-gigawatt)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} gigawatts",shortFallback: "{0} GW",narrowFallback: "{0}GW")]
        PowerGigawatt = 137,

        /// <summary>
        /// horsepower (power-horsepower)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} horsepower",shortFallback: "{0} hp",narrowFallback: "{0}hp")]
        PowerHorsepower = 138,

        /// <summary>
        /// kilowatts (power-kilowatt)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilowatts",shortFallback: "{0} kW",narrowFallback: "{0}kW")]
        PowerKilowatt = 139,

        /// <summary>
        /// megawatts (power-megawatt)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} megawatts",shortFallback: "{0} MW",narrowFallback: "{0}MW")]
        PowerMegawatt = 140,

        /// <summary>
        /// milliwatts (power-milliwatt)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} milliwatts",shortFallback: "{0} mW",narrowFallback: "{0}mW")]
        PowerMilliwatt = 141,

        /// <summary>
        /// watts (power-watt)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} watts",shortFallback: "{0} W",narrowFallback: "{0}W")]
        PowerWatt = 142,

        /// <summary>
        /// atmospheres (pressure-atmosphere)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} atmospheres",shortFallback: "{0} atm",narrowFallback: "{0}atm")]
        PressureAtmosphere = 143,

        /// <summary>
        /// bars (pressure-bar)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} bars",shortFallback: "{0} bar",narrowFallback: "{0}bar")]
        PressureBar = 144,

        /// <summary>
        /// of gasoline equivalent (pressure-gasoline-energy-density)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} of gasoline equivalent",shortFallback: "{0} gas-equiv",narrowFallback: "{0}gas-equiv")]
        PressureGasolineEnergyDensity = 145,

        /// <summary>
        /// hectopascals (pressure-hectopascal)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} hectopascals",shortFallback: "{0} hPa",narrowFallback: "{0}hPa")]
        PressureHectopascal = 146,

        /// <summary>
        /// inches of mercury (pressure-inch-ofhg)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} inches of mercury",shortFallback: "{0} inHg",narrowFallback: "{0}″ Hg")]
        PressureInchOfhg = 147,

        /// <summary>
        /// kilopascals (pressure-kilopascal)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilopascals",shortFallback: "{0} kPa",narrowFallback: "{0}kPa")]
        PressureKilopascal = 148,

        /// <summary>
        /// megapascals (pressure-megapascal)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} megapascals",shortFallback: "{0} MPa",narrowFallback: "{0}MPa")]
        PressureMegapascal = 149,

        /// <summary>
        /// millibars (pressure-millibar)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} millibars",shortFallback: "{0} mbar",narrowFallback: "{0}mb")]
        PressureMillibar = 150,

        /// <summary>
        /// millimeters of mercury (pressure-millimeter-ofhg)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} millimeters of mercury",shortFallback: "{0} mmHg",narrowFallback: "{0}mmHg")]
        PressureMillimeterOfhg = 151,

        /// <summary>
        /// pascals (pressure-pascal)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pascals",shortFallback: "{0} Pa",narrowFallback: "{0}Pa")]
        PressurePascal = 152,

        /// <summary>
        /// pounds-force per square inch (pressure-pound-force-per-square-inch)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pounds-force per square inch",shortFallback: "{0} psi",narrowFallback: "{0}psi")]
        PressurePoundForcePerSquareInch = 153,

        /// <summary>
        /// Beaufort (speed-beaufort)
        /// </summary>
        [UnitFallbackValues(longFallback: "Beaufort {0}",shortFallback: "B {0}",narrowFallback: "B{0}")]
        SpeedBeaufort = 154,

        /// <summary>
        /// kilometers per hour (speed-kilometer-per-hour)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kilometers per hour",shortFallback: "{0} km/h",narrowFallback: "{0}km/h")]
        SpeedKilometerPerHour = 155,

        /// <summary>
        /// knots (speed-knot)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} knots",shortFallback: "{0} kn",narrowFallback: "{0}kn")]
        SpeedKnot = 156,

        /// <summary>
        /// light (speed-light-speed)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} light",shortFallback: "{0} light",narrowFallback: "{0}light")]
        SpeedLightSpeed = 157,

        /// <summary>
        /// meters per second (speed-meter-per-second)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} meters per second",shortFallback: "{0} m/s",narrowFallback: "{0}m/s")]
        SpeedMeterPerSecond = 158,

        /// <summary>
        /// miles per hour (speed-mile-per-hour)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} miles per hour",shortFallback: "{0} mph",narrowFallback: "{0}mph")]
        SpeedMilePerHour = 159,

        /// <summary>
        /// degrees Celsius (temperature-celsius)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} degrees Celsius",shortFallback: "{0}°C",narrowFallback: "{0}°C")]
        TemperatureCelsius = 160,

        /// <summary>
        /// degrees Fahrenheit (temperature-fahrenheit)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} degrees Fahrenheit",shortFallback: "{0}°F",narrowFallback: "{0}°")]
        TemperatureFahrenheit = 161,

        /// <summary>
        /// degrees temperature (temperature-generic)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} degrees temperature",shortFallback: "{0}°",narrowFallback: "{0}°")]
        TemperatureGeneric = 162,

        /// <summary>
        /// kelvins (temperature-kelvin)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} kelvins",shortFallback: "{0} K",narrowFallback: "{0}K")]
        TemperatureKelvin = 163,

        /// <summary>
        /// newton-meters (torque-newton-meter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} newton-meters",shortFallback: "{0} N⋅m",narrowFallback: "{0}N⋅m")]
        TorqueNewtonMeter = 164,

        /// <summary>
        /// pound-force-feet (torque-pound-force-foot)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pound-force-feet",shortFallback: "{0} lbf⋅ft",narrowFallback: "{0}lbf⋅ft")]
        TorquePoundForceFoot = 165,

        /// <summary>
        /// acre-feet (volume-acre-foot)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} acre-feet",shortFallback: "{0} ac ft",narrowFallback: "{0}ac ft")]
        VolumeAcreFoot = 166,

        /// <summary>
        /// barrels (volume-barrel)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} barrels",shortFallback: "{0} bbl",narrowFallback: "{0}bbl")]
        VolumeBarrel = 167,

        /// <summary>
        /// bushels (volume-bushel)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} bushels",shortFallback: "{0} bu",narrowFallback: "{0}bu")]
        VolumeBushel = 168,

        /// <summary>
        /// centiliters (volume-centiliter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} centiliters",shortFallback: "{0} cL",narrowFallback: "{0}cL")]
        VolumeCentiliter = 169,

        /// <summary>
        /// cubic centimeters (volume-cubic-centimeter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cubic centimeters",shortFallback: "{0} cm³",narrowFallback: "{0}cm³")]
        VolumeCubicCentimeter = 170,

        /// <summary>
        /// cubic feet (volume-cubic-foot)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cubic feet",shortFallback: "{0} ft³",narrowFallback: "{0}ft³")]
        VolumeCubicFoot = 171,

        /// <summary>
        /// cubic inches (volume-cubic-inch)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cubic inches",shortFallback: "{0} in³",narrowFallback: "{0}in³")]
        VolumeCubicInch = 172,

        /// <summary>
        /// cubic kilometers (volume-cubic-kilometer)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cubic kilometers",shortFallback: "{0} km³",narrowFallback: "{0}km³")]
        VolumeCubicKilometer = 173,

        /// <summary>
        /// cubic meters (volume-cubic-meter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cubic meters",shortFallback: "{0} m³",narrowFallback: "{0}m³")]
        VolumeCubicMeter = 174,

        /// <summary>
        /// cubic miles (volume-cubic-mile)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cubic miles",shortFallback: "{0} mi³",narrowFallback: "{0}mi³")]
        VolumeCubicMile = 175,

        /// <summary>
        /// cubic yards (volume-cubic-yard)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cubic yards",shortFallback: "{0} yd³",narrowFallback: "{0}yd³")]
        VolumeCubicYard = 176,

        /// <summary>
        /// cups (volume-cup)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} cups",shortFallback: "{0} c",narrowFallback: "{0}c")]
        VolumeCup = 177,

        /// <summary>
        /// VolumeCupJp (volume-cup-jp)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u30AB\u30C3\u30D7",shortFallback: "{0} カップ",narrowFallback: "{0}カップ")]
        VolumeCupJp = 178,

        /// <summary>
        /// metric cups (volume-cup-metric)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} metric cups",shortFallback: "{0} mc",narrowFallback: "{0}mc")]
        VolumeCupMetric = 179,

        /// <summary>
        /// deciliters (volume-deciliter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} deciliters",shortFallback: "{0} dL",narrowFallback: "{0}dL")]
        VolumeDeciliter = 180,

        /// <summary>
        /// dessert spoons (volume-dessert-spoon)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} dessert spoons",shortFallback: "{0} dsp",narrowFallback: "{0}dsp")]
        VolumeDessertSpoon = 181,

        /// <summary>
        /// Imp. dessert spoons (volume-dessert-spoon-imperial)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} Imp. dessert spoons",shortFallback: "{0} dsp-Imp.",narrowFallback: "{0}dsp-Imp")]
        VolumeDessertSpoonImperial = 182,

        /// <summary>
        /// drams (volume-dram)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} drams",shortFallback: "{0} drams",narrowFallback: "{0}fl.dr.")]
        VolumeDram = 183,

        /// <summary>
        /// drops (volume-drop)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} drops",shortFallback: "{0} drdrops",narrowFallback: "{0}dr")]
        VolumeDrop = 184,

        /// <summary>
        /// fluid ounces (volume-fluid-ounce)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} fluid ounces",shortFallback: "{0} fl oz",narrowFallback: "{0}fl oz")]
        VolumeFluidOunce = 185,

        /// <summary>
        /// Imp. fluid ounces (volume-fluid-ounce-imperial)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} Imp. fluid ounces",shortFallback: "{0} fl oz Imp.",narrowFallback: "{0}fl oz Im")]
        VolumeFluidOunceImperial = 186,

        /// <summary>
        /// gallons (volume-gallon)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} gallons",shortFallback: "{0} gal",narrowFallback: "{0}gal")]
        VolumeGallon = 187,

        /// <summary>
        /// Imp. gallons (volume-gallon-imperial)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} Imp. gallons",shortFallback: "{0} gal Imp.",narrowFallback: "{0}galIm")]
        VolumeGallonImperial = 188,

        /// <summary>
        /// hectoliters (volume-hectoliter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} hectoliters",shortFallback: "{0} hL",narrowFallback: "{0}hL")]
        VolumeHectoliter = 189,

        /// <summary>
        /// jiggers (volume-jigger)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} jiggers",shortFallback: "{0} jiggers",narrowFallback: "{0}jigger")]
        VolumeJigger = 190,

        /// <summary>
        /// VolumeKoku (volume-koku)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u77F3",shortFallback: "{0} 石",narrowFallback: "{0}石")]
        VolumeKoku = 191,

        /// <summary>
        /// VolumeKosaji (volume-kosaji)
        /// </summary>
        [UnitFallbackValues(longFallback: "\u5C0F\u3055\u3058 {0}",shortFallback: "小さじ {0}",narrowFallback: "小さじ{0}")]
        VolumeKosaji = 192,

        /// <summary>
        /// liters (volume-liter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} liters",shortFallback: "{0} L",narrowFallback: "{0}L")]
        VolumeLiter = 193,

        /// <summary>
        /// megaliters (volume-megaliter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} megaliters",shortFallback: "{0} ML",narrowFallback: "{0}ML")]
        VolumeMegaliter = 194,

        /// <summary>
        /// milliliters (volume-milliliter)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} milliliters",shortFallback: "{0} mL",narrowFallback: "{0}mL")]
        VolumeMilliliter = 195,

        /// <summary>
        /// VolumeOsaji (volume-osaji)
        /// </summary>
        [UnitFallbackValues(longFallback: "\u5927\u3055\u3058 {0}",shortFallback: "大さじ {0}",narrowFallback: "大さじ{0}")]
        VolumeOsaji = 196,

        /// <summary>
        /// pinches (volume-pinch)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pinches",shortFallback: "{0} pn",narrowFallback: "{0}pn")]
        VolumePinch = 197,

        /// <summary>
        /// pints (volume-pint)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} pints",shortFallback: "{0} pt",narrowFallback: "{0}pt")]
        VolumePint = 198,

        /// <summary>
        /// metric pints (volume-pint-metric)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} metric pints",shortFallback: "{0} mpt",narrowFallback: "{0}mpt")]
        VolumePintMetric = 199,

        /// <summary>
        /// quarts (volume-quart)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} quarts",shortFallback: "{0} qt",narrowFallback: "{0}qt")]
        VolumeQuart = 200,

        /// <summary>
        /// Imp. quarts (volume-quart-imperial)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} Imp. quarts",shortFallback: "{0} qt-Imp.",narrowFallback: "{0}qt-Imp.")]
        VolumeQuartImperial = 201,

        /// <summary>
        /// VolumeSai (volume-sai)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u624D",shortFallback: "{0} 才",narrowFallback: "{0}才")]
        VolumeSai = 202,

        /// <summary>
        /// VolumeShaku (volume-shaku)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u52FA",shortFallback: "{0} 勺",narrowFallback: "{0}勺")]
        VolumeShaku = 203,

        /// <summary>
        /// tablespoons (volume-tablespoon)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} tablespoons",shortFallback: "{0} tbsp",narrowFallback: "{0}tbsp")]
        VolumeTablespoon = 204,

        /// <summary>
        /// teaspoons (volume-teaspoon)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} teaspoons",shortFallback: "{0} tsp",narrowFallback: "{0}tsp")]
        VolumeTeaspoon = 205,

        /// <summary>
        /// VolumeToJp (volume-to-jp)
        /// </summary>
        [UnitFallbackValues(longFallback: "{0} \u6597",shortFallback: "{0} 斗",narrowFallback: "{0}斗")]
        VolumeToJp = 206,
    }
}
